#!/bin/sh
# Copyright (c) 2021, chris1111. All Right Reserved
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# Vars
SLEDir="/System/Volumes/Update/mnt1/System/Library/Extensions/"
TempDir="/Private/tmp/Install"
BUSLEDir="$HOME/Desktop/BackupKext_SLE"
echo " "
if [ "/Private/tmp/Install" ]; then
    rm -rf "/Private/tmp/Install"
fi
echo "
******************************************************
Command Line Install Kext ➤ Start
******************************************************"
# Set Droping directory and file
mkdir -p "${TempDir}"
echo  "`tput setaf 7``tput sgr0``tput bold``tput setaf 10`Please move your kexts to the window \ Followed by Enter`tput sgr0` `tput setaf 7``tput sgr0`  "
read -p ": " target
cp -R ${target} "${TempDir}"
echo "Prepare Installation for:"
for file in "${TempDir}"/*;
do
echo "${file##*/}"
done
Sleep 1
echo "Verifying Kexts for /System/Library/Extensions/:"
if [ -e "${3}/System/Volumes/Update/mnt1/System/Library/Extensions/${file##*/}"  ]; then
echo "Find ${file##*/} ➣ Save Kext for (SLE)"
mkdir -p ~/Desktop/BackupKext_SLE
for file in "${TempDir}"/*;
do
Sleep 3
rsync -ab "${TempDir}"/${file##*/} "$BUSLEDir";
Sleep 1
done
fi
sudo cp -r /Private/tmp/Install/* "${SLEDir}"
Sleep 1
echo "Kext Cache repair! Please wait. ."
sudo chown -R root:wheel /System/Volumes/Update/mnt1/System/Library/Extensions
sudo chmod -R 755 /System/Volumes/Update/mnt1/System/Library/Extensions
sudo kmutil install --volume-root /System/Volumes/Update/mnt1/ --update-all
sudo bless --folder /System/Volumes/Update/mnt1/System/Library/CoreServices --bootefi --create-snapshot
Sleep 1
diskutil unmount /System/Volumes/Update/mnt1
echo "Done! Reboot your mac"
Sleep 1
mv ~/Desktop/BackupKext_SLE ~/Desktop/BackupKext_SLE`date "+%Y%m%d_%H%M%S"`
sudo rm -rf /Private/tmp/Install
